---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  The function will run on an hourly basis and stop or start AWS instances according to a schedule defined in `AUTO_START` or `AUTO_STOP` Tags.

  Schedule Tag values consists of an hour with an optional timezone (the default is `UTC`) and optionally the week days to which the schedule applies.


Resources:
  EC2StopStart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: main.lambda_handler
      Runtime: python3.6
      Timeout: 300
      MemorySize: 128
      Events:
        Hourly:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Policies:
      - Version: "2012-10-17"
        Statement: 
        - Effect: Allow
          Action:
          - ec2:DescribeInstances
          - ec2:StartInstances
          - ec2:StopInstances
          - kms:CreateGrant  
          Resource: "*"


Metadata:
  AWS::ServerlessRepo::Application:
    Name: stop-start-on-tag
    Description: Stop or start AWS instances according to a schedule defined in `AUTO_START` or `AUTO_STOP` Tags.
    Author: Equancy
    SpdxLicenseId: MIT
    LicenseUrl: ./LICENSE
    ReadmeUrl: ./README.md
    Labels:
    - EC2
    - Stop
    - Start
    HomePageUrl: https://github.com/equancy/aws-sam-stopstart
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/equancy/aws-sam-stopstart